package mcp

import (
	"bytes"
	"encoding/base64"
	"encoding/json"
	"net/http"
	"net/url"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"testing"

	"github.com/modelcontextprotocol/go-sdk/mcp"
	"github.com/wishmatic/nano-mcp/internal/resolve"
)

const testImageCost = 0.04

func TestGenerateImageToolIsListed(t *testing.T) {
	session := nanoSession(t, "http://127.0.0.1:1")

	props := toolProperties(t, findTool(t, session, "generate_image"))

	want := []string{
		"prompt", "model", "n", "size", "image", "images", "mask", "seed", "strength", "guidanceScale",
		"numInferenceSteps",
	}

	for _, name := range want {
		if _, ok := props[name]; !ok {
			t.Errorf("the input schema has no %q", name)
		}
	}
}

func TestGenerateImageStoresAndAttachesWhatItGenerates(t *testing.T) {
	nano, submits := recordingImageNano(t, inlineResponse(testPNGBytes, testImageCost))

	store, dir := videoStore(t)

	deps := noopDeps()
	deps.NanoGPT = nanoClient(t, nano)
	deps.Files = store
	deps.Resolver = addressMap(t, "")

	result := callTool(t, connectedSession(t, deps), "generate_image", map[string]any{
		"prompt": "a lake at sunset",
		"model":  "nano-banana",
	})

	if result.IsError {
		t.Fatalf("generate_image failed: %s", errorText(result))
	}

	if len(result.Content) != 2 {
		t.Fatalf("content = %#v, want the URL and the image", result.Content)
	}

	text, ok := result.Content[0].(*mcp.TextContent)
	if !ok {
		t.Fatalf("content[0] = %T, want the URL as text", result.Content[0])
	}

	image, ok := result.Content[1].(*mcp.ImageContent)
	if !ok {
		t.Fatalf("content[1] = %T, want the image itself rather than a link", result.Content[1])
	}

	if image.MIMEType != "image/png" || !bytes.Equal(image.Data, testPNGBytes) {
		t.Errorf("image = %q of %d bytes, want the generated png", image.MIMEType, len(image.Data))
	}

	if image.Annotations == nil || !slices.Equal(image.Annotations.Audience, []mcp.Role{"user", "assistant"}) {
		t.Errorf("audience = %+v, want [user assistant], so a vision model can see it", image.Annotations)
	}

	var out struct {
		Model   string   `json:"model"`
		Count   int      `json:"count"`
		URLs    []string `json:"urls"`
		CostUSD float64  `json:"costUsd"`
	}
	structured(t, result, &out)

	if out.Model != "nano-banana" || out.Count != 1 || out.CostUSD != testImageCost {
		t.Errorf("output = %+v, want the model, one image, and the charged cost", out)
	}

	if len(out.URLs) != 1 || out.URLs[0] != text.Text {
		t.Errorf("output urls = %v, want the URL the text block carries", out.URLs)
	}

	parsed, err := url.Parse(text.Text)
	if err != nil {
		t.Fatalf("url.Parse() error: %v", err)
	}

	if parsed.Host != "nano.example.com" || !strings.HasSuffix(parsed.Path, ".png") {
		t.Errorf("url = %q, want it served as a png from the public host", text.Text)
	}

	key := filepath.FromSlash(strings.TrimPrefix(parsed.Path, "/"))

	stored, err := os.ReadFile(filepath.Join(dir, key))
	if err != nil {
		t.Fatalf("read the hosted copy: %v", err)
	}

	if !bytes.Equal(stored, testPNGBytes) {
		t.Errorf("hosted copy = %q, want the generated bytes", stored)
	}

	if body := submits.body(t); body["response_format"] != "b64_json" {
		t.Errorf("response_format = %v, want the inline form this server stores", body["response_format"])
	}
}

func TestGenerateImageCopiesTheURLItFallsBackTo(t *testing.T) {
	source := servePNG(t)

	deps := noopDeps()
	deps.NanoGPT = nanoClient(t, upstreamJSON(t, `{"data":[{"url":"`+source+`/out.png"}]}`))
	deps.Files = fileStore(t)
	deps.Resolver = addressMap(t, "")

	result := callTool(t, connectedSession(t, deps), "generate_image", map[string]any{"prompt": "a lake"})

	if result.IsError {
		t.Fatalf("generate_image failed: %s", errorText(result))
	}

	if len(result.Content) != 2 {
		t.Fatalf("content = %#v, want the URL and the image", result.Content)
	}

	image, ok := result.Content[1].(*mcp.ImageContent)
	if !ok {
		t.Fatalf("content[1] = %T, want the image itself", result.Content[1])
	}

	if image.MIMEType != "image/png" || !bytes.Equal(image.Data, testPNGBytes) {
		t.Errorf("image = %q of %d bytes, want the bytes the fallback URL served", image.MIMEType, len(image.Data))
	}
}

func TestGenerateImageSendsTheResolvedAddresses(t *testing.T) {
	nano, submits := recordingImageNano(t, inlineResponse(testPNGBytes, 0))

	want := "data:image/png;base64," + base64.StdEncoding.EncodeToString(testPNGBytes)

	result := generateImage(t, nano, addressMap(t, ""), map[string]any{
		"prompt": "make it snow",
		"image":  want,
		"images": []string{want},
		"mask":   want,
	})

	if result.IsError {
		t.Fatalf("generate_image failed: %s", errorText(result))
	}

	body := submits.body(t)

	for _, key := range []string{"imageDataUrl", "maskDataUrl"} {
		if body[key] != want {
			t.Errorf("%s = %v, want the resolved data URL", key, body[key])
		}
	}

	if urls, ok := body["imageDataUrls"].([]any); !ok || !slices.Equal(urls, []any{want}) {
		t.Errorf("imageDataUrls = %v, want the resolved data URL", body["imageDataUrls"])
	}
}

func TestGenerateImageSendsWhatTheCallerNarrowed(t *testing.T) {
	nano, submits := recordingImageNano(t, inlineResponse(testPNGBytes, 0))

	result := generateImage(t, nano, addressMap(t, ""), map[string]any{
		"prompt":            "a lake",
		"n":                 2,
		"size":              "1024x1024",
		"seed":              42,
		"strength":          0.6,
		"guidanceScale":     7.5,
		"numInferenceSteps": 30,
	})

	if result.IsError {
		t.Fatalf("generate_image failed: %s", errorText(result))
	}

	body := submits.body(t)

	for key, value := range map[string]any{
		"n":                   float64(2),
		"size":                "1024x1024",
		"seed":                float64(42),
		"strength":            0.6,
		"guidance_scale":      7.5,
		"num_inference_steps": float64(30),
	} {
		if body[key] != value {
			t.Errorf("body[%q] = %v, want %v", key, body[key], value)
		}
	}

	for _, key := range []string{"imageDataUrl", "maskDataUrl", "imageDataUrls"} {
		if _, ok := body[key]; ok {
			t.Errorf("body[%q] = %v, want it omitted", key, body[key])
		}
	}
}

func TestGenerateImageReportsAnUpstreamRefusal(t *testing.T) {
	deps := noopDeps()
	deps.NanoGPT = nanoClient(t, upstream(t, func(w http.ResponseWriter, _ *http.Request) {
		w.WriteHeader(http.StatusPaymentRequired)
		_, _ = w.Write([]byte(`{"message":"out of credit"}`))
	}))
	deps.Files = fileStore(t)
	deps.Resolver = addressMap(t, "")

	result := callTool(t, connectedSession(t, deps), "generate_image", map[string]any{"prompt": "a lake"})

	if !result.IsError {
		t.Fatal("generate_image succeeded, want the refusal surfaced")
	}

	text := errorText(result)
	if !strings.Contains(text, "402") || !strings.Contains(text, "out of credit") {
		t.Errorf("error = %q, want the status and the message", text)
	}
}

func TestGenerateImageNeedsAPrompt(t *testing.T) {
	deps := noopDeps()
	deps.NanoGPT = nanoClient(t, "http://127.0.0.1:1")
	deps.Files = fileStore(t)
	deps.Resolver = addressMap(t, "")

	result := callTool(t, connectedSession(t, deps), "generate_image", map[string]any{"model": "nano-banana"})

	if !result.IsError || !strings.Contains(errorText(result), "required") {
		t.Errorf("result = %#v, want the missing field named", result.Content)
	}
}

func TestGenerateImageRefusesAnImageItCannotUse(t *testing.T) {
	deps := noopDeps()
	deps.NanoGPT = nanoClient(t, upstream(t, func(_ http.ResponseWriter, r *http.Request) {
		t.Errorf("the upstream was called for an image that cannot be resolved: %s", r.URL.Path)
	}))
	deps.Files = fileStore(t)
	deps.Resolver = addressMap(t, "")

	result := callTool(t, connectedSession(t, deps), "generate_image", map[string]any{
		"prompt": "a lake",
		"image":  "data:image/gif;base64," + base64.StdEncoding.EncodeToString([]byte("GIF89a")),
	})

	if !result.IsError || !strings.Contains(errorText(result), "image/gif") {
		t.Errorf("result = %#v, want the unsupported type named", result.Content)
	}
}

func TestGenerateImageRefusesBytesItCannotServe(t *testing.T) {
	deps := noopDeps()
	deps.NanoGPT = nanoClient(t, upstreamJSON(t,
		inlineResponse([]byte("this is not an image at all, whatever it is"), 0)))
	deps.Files = fileStore(t)
	deps.Resolver = addressMap(t, "")

	result := callTool(t, connectedSession(t, deps), "generate_image", map[string]any{"prompt": "a lake"})

	if !result.IsError || !strings.Contains(errorText(result), "not a type this server serves") {
		t.Errorf("result = %#v, want the unusable bytes refused", result.Content)
	}
}

func TestServerWithoutFileStorageListsNoStorageTools(t *testing.T) {
	deps := noopDeps()
	deps.NanoGPT = nanoClient(t, "http://127.0.0.1:1")

	session := connectedSession(t, deps)

	names := toolNames(t, session)

	for _, name := range []string{"generate_image", "generate_video"} {
		if slices.Contains(names, name) {
			t.Errorf("tools = %v, want no %s until storage is configured", names, name)
		}
	}
}

func generateImage(t *testing.T, nano string, resolver *resolve.Client, args map[string]any) *mcp.CallToolResult {
	t.Helper()

	deps := noopDeps()
	deps.NanoGPT = nanoClient(t, nano)
	deps.Files = fileStore(t)
	deps.Resolver = resolver

	return callTool(t, connectedSession(t, deps), "generate_image", args)
}

// inlineResponse is the shape nano-gpt answers with when it has the bytes to hand, which is what
// asking for b64_json is for.
func inlineResponse(image []byte, cost float64) string {
	body, err := json.Marshal(map[string]any{
		"created": 1,
		"data": []map[string]string{
			{"b64_json": base64.StdEncoding.EncodeToString(image)},
		},
		"cost": cost,
	})
	if err != nil {
		panic(err)
	}

	return string(body)
}

// recordingImageNano answers one image generation, keeping the request body so a test can check
// what was sent.
func recordingImageNano(t *testing.T, response string) (string, *submitRecorder) {
	t.Helper()

	recorder := &submitRecorder{}

	nano := upstream(t, func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost || r.URL.Path != "/api/v1/images/generations" {
			t.Errorf("upstream call = %s %s, want the images endpoint", r.Method, r.URL.Path)
		}

		var body map[string]any
		if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
			t.Errorf("decode image body: %v", err)
		}

		recorder.mu.Lock()
		recorder.submit = body
		recorder.mu.Unlock()

		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte(response))
	})

	return nano, recorder
}

func upstreamJSON(t *testing.T, body string) string {
	t.Helper()

	return upstream(t, func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte(body))
	})
}

func servePNG(t *testing.T) string {
	t.Helper()

	return upstream(t, func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("Content-Type", "application/octet-stream")
		_, _ = w.Write(testPNGBytes)
	})
}
